<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23setContainer' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getParameter' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getSubscribedServices' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23has' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23get' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23generateUrl' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23forward' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23redirect' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23redirectToRoute' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23json' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23file' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23addFlash' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23isGranted' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23denyAccessUnlessGranted' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23renderView' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23render' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23renderForm' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23stream' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createNotFoundException' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createAccessDeniedException' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createForm' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createFormBuilder' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getDoctrine' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getUser' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23isCsrfTokenValid' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23dispatchMessage' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23addLink' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%24container' => 0,
'Contao%5CCoreBundle%5CController%5CAbstractBackendController' => 0,
'Contao%5CCoreBundle%5CController%5CAbstractBackendController%23render' => 0,
'Contao%5CCoreBundle%5CController%5CAbstractController%23getSubscribedServices' => 0,
'Contao%5CCoreBundle%5CController%5CAbstractController%23initializeContaoFramework' => 0,
'Contao%5CCoreBundle%5CController%5CAbstractController%23getContaoAdapter' => 0,
'Contao%5CCoreBundle%5CController%5CAbstractController%23tagResponse' => 0,
'Contao%5CCoreBundle%5CController%5CAbstractController%23getCsrfFormOptions' => 0,
'Contao%5CCoreBundle%5CController%5CAbstractController' => 0,
'Contao%5CCoreBundle%5CController%5CAbstractFragmentController' => 0,
'Contao%5CCoreBundle%5CController%5CAbstractFragmentController%23setFragmentOptions' => 0,
'Contao%5CCoreBundle%5CController%5CAbstractFragmentController%23getSubscribedServices' => 0,
'Contao%5CCoreBundle%5CController%5CAbstractFragmentController%23getPageModel' => 0,
'Contao%5CCoreBundle%5CController%5CAbstractFragmentController%23createTemplate' => 0,
'Contao%5CCoreBundle%5CController%5CAbstractFragmentController%23addHeadlineToTemplate' => 0,
'Contao%5CCoreBundle%5CController%5CAbstractFragmentController%23addCssAttributesToTemplate' => 0,
'Contao%5CCoreBundle%5CController%5CAbstractFragmentController%23addPropertiesToTemplate' => 0,
'Contao%5CCoreBundle%5CController%5CAbstractFragmentController%23addSectionToTemplate' => 0,
'Contao%5CCoreBundle%5CController%5CAbstractFragmentController%23getType' => 0,
'Contao%5CCoreBundle%5CController%5CAbstractFragmentController%23render' => 0,
'Contao%5CCoreBundle%5CController%5CAbstractFragmentController%23markResponseForInternalCaching' => 0,
'Contao%5CCoreBundle%5CController%5CAbstractFragmentController%24options' => 0,
'Contao%5CCoreBundle%5CController%5CBackendController' => 1,
'Contao%5CCoreBundle%5CController%5CBackendController%23mainAction' => 2,
'Contao%5CCoreBundle%5CController%5CBackendController%23loginAction' => 3,
'Contao%5CCoreBundle%5CController%5CBackendController%23logoutAction' => 4,
'Contao%5CCoreBundle%5CController%5CBackendController%23passwordAction' => 5,
'Contao%5CCoreBundle%5CController%5CBackendController%23confirmAction' => 6,
'Contao%5CCoreBundle%5CController%5CBackendController%23fileAction' => 7,
'Contao%5CCoreBundle%5CController%5CBackendController%23helpAction' => 8,
'Contao%5CCoreBundle%5CController%5CBackendController%23pageAction' => 9,
'Contao%5CCoreBundle%5CController%5CBackendController%23popupAction' => 10,
'Contao%5CCoreBundle%5CController%5CBackendController%23alertsAction' => 11,
'Contao%5CCoreBundle%5CController%5CBackendController%23pickerAction' => 12,
'Contao%5CCoreBundle%5CController%5CBackendController%23backendFallback' => 13,
'Contao%5CCoreBundle%5CController%5CBackendController%23getSubscribedServices' => 0,
'Contao%5CCoreBundle%5CController%5CBackendCsvImportController' => 0,
'Contao%5CCoreBundle%5CController%5CBackendCsvImportController%23__construct' => 0,
'Contao%5CCoreBundle%5CController%5CBackendCsvImportController%23importListWizardAction' => 0,
'Contao%5CCoreBundle%5CController%5CBackendCsvImportController%23importTableWizardAction' => 0,
'Contao%5CCoreBundle%5CController%5CBackendCsvImportController%23importOptionWizardAction' => 0,
'Contao%5CCoreBundle%5CController%5CBackendCsvImportController%23importFromTemplate' => 0,
'Contao%5CCoreBundle%5CController%5CBackendCsvImportController%23prepareTemplate' => 0,
'Contao%5CCoreBundle%5CController%5CBackendCsvImportController%23fetchData' => 0,
'Contao%5CCoreBundle%5CController%5CBackendCsvImportController%23getFormId' => 0,
'Contao%5CCoreBundle%5CController%5CBackendCsvImportController%23getBackUrl' => 0,
'Contao%5CCoreBundle%5CController%5CBackendCsvImportController%23getSeparators' => 0,
'Contao%5CCoreBundle%5CController%5CBackendCsvImportController%23getDelimiter' => 0,
'Contao%5CCoreBundle%5CController%5CBackendCsvImportController%23getFiles' => 0,
'Contao%5CCoreBundle%5CController%5CBackendCsvImportController%24framework' => 0,
'Contao%5CCoreBundle%5CController%5CBackendCsvImportController%24connection' => 0,
'Contao%5CCoreBundle%5CController%5CBackendCsvImportController%24requestStack' => 0,
'Contao%5CCoreBundle%5CController%5CBackendCsvImportController%24translator' => 0,
'Contao%5CCoreBundle%5CController%5CBackendCsvImportController%24projectDir' => 0,
'Contao%5CCoreBundle%5CController%5CBackendPreviewController' => 14,
'Contao%5CCoreBundle%5CController%5CBackendPreviewController%23__construct' => 0,
'Contao%5CCoreBundle%5CController%5CBackendPreviewController%23__invoke' => 0,
'Contao%5CCoreBundle%5CController%5CBackendPreviewController%24previewScript' => 0,
'Contao%5CCoreBundle%5CController%5CBackendPreviewController%24previewAuthenticator' => 0,
'Contao%5CCoreBundle%5CController%5CBackendPreviewController%24dispatcher' => 0,
'Contao%5CCoreBundle%5CController%5CBackendPreviewController%24authorizationChecker' => 0,
'Contao%5CCoreBundle%5CController%5CBackendPreviewSwitchController' => 15,
'Contao%5CCoreBundle%5CController%5CBackendPreviewSwitchController%23__construct' => 0,
'Contao%5CCoreBundle%5CController%5CBackendPreviewSwitchController%23__invoke' => 0,
'Contao%5CCoreBundle%5CController%5CBackendPreviewSwitchController%23renderToolbar' => 0,
'Contao%5CCoreBundle%5CController%5CBackendPreviewSwitchController%23authenticatePreview' => 0,
'Contao%5CCoreBundle%5CController%5CBackendPreviewSwitchController%23getMembersDataList' => 0,
'Contao%5CCoreBundle%5CController%5CBackendPreviewSwitchController%24previewAuthenticator' => 0,
'Contao%5CCoreBundle%5CController%5CBackendPreviewSwitchController%24tokenChecker' => 0,
'Contao%5CCoreBundle%5CController%5CBackendPreviewSwitchController%24connection' => 0,
'Contao%5CCoreBundle%5CController%5CBackendPreviewSwitchController%24security' => 0,
'Contao%5CCoreBundle%5CController%5CBackendPreviewSwitchController%24twig' => 0,
'Contao%5CCoreBundle%5CController%5CBackendPreviewSwitchController%24router' => 0,
'Contao%5CCoreBundle%5CController%5CBackendPreviewSwitchController%24tokenManager' => 0,
'Contao%5CCoreBundle%5CController%5CBackendPreviewSwitchController%24translator' => 0,
'Contao%5CCoreBundle%5CController%5CBackendPreviewSwitchController%24backendAttributes' => 0,
'Contao%5CCoreBundle%5CController%5CBackendPreviewSwitchController%24backendBadgeTitle' => 0,
'Contao%5CCoreBundle%5CController%5CCaptchaController' => 0,
'Contao%5CCoreBundle%5CController%5CCaptchaController%23__construct' => 0,
'Contao%5CCoreBundle%5CController%5CCaptchaController%23__invoke' => 16,
'Contao%5CCoreBundle%5CController%5CCaptchaController%23getScriptSource' => 0,
'Contao%5CCoreBundle%5CController%5CCaptchaController%24framework' => 0,
'Contao%5CCoreBundle%5CController%5CContentElement%5CAbstractContentElementController' => 0,
'Contao%5CCoreBundle%5CController%5CContentElement%5CAbstractContentElementController%23__invoke' => 0,
'Contao%5CCoreBundle%5CController%5CContentElement%5CAbstractContentElementController%23addSharedMaxAgeToResponse' => 0,
'Contao%5CCoreBundle%5CController%5CContentElement%5CAbstractContentElementController%23getResponse' => 0,
'Contao%5CCoreBundle%5CController%5CContentElement%5CMarkdownController' => 0,
'Contao%5CCoreBundle%5CController%5CContentElement%5CMarkdownController%23getSubscribedServices' => 0,
'Contao%5CCoreBundle%5CController%5CContentElement%5CMarkdownController%23getResponse' => 0,
'Contao%5CCoreBundle%5CController%5CContentElement%5CMarkdownController%23createConverter' => 0,
'Contao%5CCoreBundle%5CController%5CContentElement%5CMarkdownController%23getContentFromFile' => 0,
'Contao%5CCoreBundle%5CController%5CContentElement%5CTemplateController' => 0,
'Contao%5CCoreBundle%5CController%5CContentElement%5CTemplateController%23getResponse' => 0,
'Contao%5CCoreBundle%5CController%5CFaviconController' => 17,
'Contao%5CCoreBundle%5CController%5CFaviconController%23__construct' => 0,
'Contao%5CCoreBundle%5CController%5CFaviconController%23__invoke' => 18,
'Contao%5CCoreBundle%5CController%5CFaviconController%24framework' => 0,
'Contao%5CCoreBundle%5CController%5CFaviconController%24projectDir' => 0,
'Contao%5CCoreBundle%5CController%5CFaviconController%24entityCacheTags' => 0,
'Contao%5CCoreBundle%5CController%5CFrontendController' => 17,
'Contao%5CCoreBundle%5CController%5CFrontendController%23indexAction' => 0,
'Contao%5CCoreBundle%5CController%5CFrontendController%23cronAction' => 19,
'Contao%5CCoreBundle%5CController%5CFrontendController%23shareAction' => 20,
'Contao%5CCoreBundle%5CController%5CFrontendController%23logoutAction' => 21,
'Contao%5CCoreBundle%5CController%5CFrontendController%23checkCookiesAction' => 22,
'Contao%5CCoreBundle%5CController%5CFrontendController%23requestTokenScriptAction' => 23,
'Contao%5CCoreBundle%5CController%5CFrontendController%23getSubscribedServices' => 0,
'Contao%5CCoreBundle%5CController%5CFrontendModule%5CAbstractFrontendModuleController' => 0,
'Contao%5CCoreBundle%5CController%5CFrontendModule%5CAbstractFrontendModuleController%23__invoke' => 0,
'Contao%5CCoreBundle%5CController%5CFrontendModule%5CAbstractFrontendModuleController%23getSubscribedServices' => 0,
'Contao%5CCoreBundle%5CController%5CFrontendModule%5CAbstractFrontendModuleController%23getBackendWildcard' => 0,
'Contao%5CCoreBundle%5CController%5CFrontendModule%5CAbstractFrontendModuleController%23getResponse' => 0,
'Contao%5CCoreBundle%5CController%5CFrontendModule%5CRootPageDependentModulesController' => 0,
'Contao%5CCoreBundle%5CController%5CFrontendModule%5CRootPageDependentModulesController%23__invoke' => 0,
'Contao%5CCoreBundle%5CController%5CFrontendModule%5CRootPageDependentModulesController%23getResponse' => 0,
'Contao%5CCoreBundle%5CController%5CFrontendModule%5CTemplateController' => 0,
'Contao%5CCoreBundle%5CController%5CFrontendModule%5CTemplateController%23getResponse' => 0,
'Contao%5CCoreBundle%5CController%5CFrontendModule%5CTwoFactorController' => 0,
'Contao%5CCoreBundle%5CController%5CFrontendModule%5CTwoFactorController%23__invoke' => 0,
'Contao%5CCoreBundle%5CController%5CFrontendModule%5CTwoFactorController%23getSubscribedServices' => 0,
'Contao%5CCoreBundle%5CController%5CFrontendModule%5CTwoFactorController%23getResponse' => 0,
'Contao%5CCoreBundle%5CController%5CFrontendModule%5CTwoFactorController%23enableTwoFactor' => 0,
'Contao%5CCoreBundle%5CController%5CFrontendModule%5CTwoFactorController%23disableTwoFactor' => 0,
'Contao%5CCoreBundle%5CController%5CFrontendModule%5CTwoFactorController%24pageModel' => 0,
'Contao%5CCoreBundle%5CController%5CImagesController' => 0,
'Contao%5CCoreBundle%5CController%5CImagesController%23__construct' => 0,
'Contao%5CCoreBundle%5CController%5CImagesController%23__invoke' => 0,
'Contao%5CCoreBundle%5CController%5CImagesController%24imageFactory' => 0,
'Contao%5CCoreBundle%5CController%5CImagesController%24resizer' => 0,
'Contao%5CCoreBundle%5CController%5CImagesController%24targetDir' => 0,
'Contao%5CCoreBundle%5CController%5CImagesController%24filesystem' => 0,
'Contao%5CCoreBundle%5CController%5CInitializeController' => 24,
'Contao%5CCoreBundle%5CController%5CInitializeController%23__construct' => 0,
'Contao%5CCoreBundle%5CController%5CInitializeController%23__invoke' => 0,
'Contao%5CCoreBundle%5CController%5CInitializeController%23handleException' => 0,
'Contao%5CCoreBundle%5CController%5CInitializeController%23handleResponse' => 0,
'Contao%5CCoreBundle%5CController%5CInitializeController%24framework' => 0,
'Contao%5CCoreBundle%5CController%5CInitializeController%24requestStack' => 0,
'Contao%5CCoreBundle%5CController%5CInitializeController%24eventDispatcher' => 0,
'Contao%5CCoreBundle%5CController%5CInitializeController%24httpKernel' => 0,
'Contao%5CCoreBundle%5CController%5CInitializeController%24kernel' => 0,
'Contao%5CCoreBundle%5CController%5CInitializeController%24hasExceptionResponse' => 0,
'Contao%5CCoreBundle%5CController%5CInsertTagsController' => 0,
'Contao%5CCoreBundle%5CController%5CInsertTagsController%23__construct' => 0,
'Contao%5CCoreBundle%5CController%5CInsertTagsController%23renderAction' => 0,
'Contao%5CCoreBundle%5CController%5CInsertTagsController%24insertTagParser' => 0,
'Contao%5CCoreBundle%5CController%5CPage%5CErrorPageController' => 25,
'Contao%5CCoreBundle%5CController%5CPage%5CErrorPageController%23__construct' => 0,
'Contao%5CCoreBundle%5CController%5CPage%5CErrorPageController%23__invoke' => 0,
'Contao%5CCoreBundle%5CController%5CPage%5CErrorPageController%23supportsContentComposition' => 0,
'Contao%5CCoreBundle%5CController%5CPage%5CErrorPageController%24framework' => 0,
'Contao%5CCoreBundle%5CController%5CPage%5CRootPageController' => 26,
'Contao%5CCoreBundle%5CController%5CPage%5CRootPageController%23__construct' => 0,
'Contao%5CCoreBundle%5CController%5CPage%5CRootPageController%23__invoke' => 0,
'Contao%5CCoreBundle%5CController%5CPage%5CRootPageController%23getNextPage' => 0,
'Contao%5CCoreBundle%5CController%5CPage%5CRootPageController%24logger' => 0,
'Contao%5CCoreBundle%5CController%5CPreviewLinkController' => 27,
'Contao%5CCoreBundle%5CController%5CPreviewLinkController%23__construct' => 0,
'Contao%5CCoreBundle%5CController%5CPreviewLinkController%23__invoke' => 28,
'Contao%5CCoreBundle%5CController%5CPreviewLinkController%24previewAuthenticator' => 0,
'Contao%5CCoreBundle%5CController%5CPreviewLinkController%24uriSigner' => 0,
'Contao%5CCoreBundle%5CController%5CPreviewLinkController%24connection' => 0,
'Contao%5CCoreBundle%5CController%5CRobotsTxtController' => 17,
'Contao%5CCoreBundle%5CController%5CRobotsTxtController%23__construct' => 0,
'Contao%5CCoreBundle%5CController%5CRobotsTxtController%23__invoke' => 29,
'Contao%5CCoreBundle%5CController%5CRobotsTxtController%24framework' => 0,
'Contao%5CCoreBundle%5CController%5CRobotsTxtController%24eventDispatcher' => 0,
'Contao%5CCoreBundle%5CController%5CSitemapController' => 17,
'Contao%5CCoreBundle%5CController%5CSitemapController%23__construct' => 0,
'Contao%5CCoreBundle%5CController%5CSitemapController%23__invoke' => 30,
'Contao%5CCoreBundle%5CController%5CSitemapController%23callLegacyHook' => 0,
'Contao%5CCoreBundle%5CController%5CSitemapController%23getPageAndArticleUrls' => 0,
'Contao%5CCoreBundle%5CController%5CSitemapController%24pageRegistry' => 0,
'Contao%5CCoreBundle%5CEntity%5CCrawlQueue' => 31,
'Contao%5CCoreBundle%5CEntity%5CCrawlQueue%24id' => 32,
'Contao%5CCoreBundle%5CEntity%5CCrawlQueue%24jobId' => 33,
'Contao%5CCoreBundle%5CEntity%5CCrawlQueue%24uri' => 34,
'Contao%5CCoreBundle%5CEntity%5CCrawlQueue%24uriHash' => 35,
'Contao%5CCoreBundle%5CEntity%5CCrawlQueue%24foundOn' => 36,
'Contao%5CCoreBundle%5CEntity%5CCrawlQueue%24level' => 37,
'Contao%5CCoreBundle%5CEntity%5CCrawlQueue%24processed' => 38,
'Contao%5CCoreBundle%5CEntity%5CCrawlQueue%24tags' => 39,
'Contao%5CCoreBundle%5CEntity%5CCronJob' => 40,
'Contao%5CCoreBundle%5CEntity%5CCronJob%23__construct' => 0,
'Contao%5CCoreBundle%5CEntity%5CCronJob%23getName' => 0,
'Contao%5CCoreBundle%5CEntity%5CCronJob%23setLastRun' => 0,
'Contao%5CCoreBundle%5CEntity%5CCronJob%23getLastRun' => 0,
'Contao%5CCoreBundle%5CEntity%5CCronJob%24id' => 32,
'Contao%5CCoreBundle%5CEntity%5CCronJob%24name' => 41,
'Contao%5CCoreBundle%5CEntity%5CCronJob%24lastRun' => 42,
'Contao%5CCoreBundle%5CEntity%5CRememberMe' => 43,
'Contao%5CCoreBundle%5CEntity%5CRememberMe%23__construct' => 0,
'Contao%5CCoreBundle%5CEntity%5CRememberMe%23__clone' => 0,
'Contao%5CCoreBundle%5CEntity%5CRememberMe%23getSeries' => 0,
'Contao%5CCoreBundle%5CEntity%5CRememberMe%23getValue' => 0,
'Contao%5CCoreBundle%5CEntity%5CRememberMe%23getLastUsed' => 0,
'Contao%5CCoreBundle%5CEntity%5CRememberMe%23getExpires' => 0,
'Contao%5CCoreBundle%5CEntity%5CRememberMe%23setExpiresInSeconds' => 0,
'Contao%5CCoreBundle%5CEntity%5CRememberMe%23getClass' => 0,
'Contao%5CCoreBundle%5CEntity%5CRememberMe%23getUsername' => 0,
'Contao%5CCoreBundle%5CEntity%5CRememberMe%23cloneWithNewValue' => 0,
'Contao%5CCoreBundle%5CEntity%5CRememberMe%24id' => 32,
'Contao%5CCoreBundle%5CEntity%5CRememberMe%24series' => 44,
'Contao%5CCoreBundle%5CEntity%5CRememberMe%24value' => 45,
'Contao%5CCoreBundle%5CEntity%5CRememberMe%24lastUsed' => 42,
'Contao%5CCoreBundle%5CEntity%5CRememberMe%24expires' => 46,
'Contao%5CCoreBundle%5CEntity%5CRememberMe%24class' => 47,
'Contao%5CCoreBundle%5CEntity%5CRememberMe%24username' => 48,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice' => 49,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice%23__construct' => 0,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice%23getId' => 0,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice%23setId' => 0,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice%23getCreated' => 0,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice%23setCreated' => 0,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice%23getUserId' => 0,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice%23setUserAgent' => 0,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice%23getUaFamily' => 0,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice%23setUaFamily' => 0,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice%23getOsFamily' => 0,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice%23setOsFamily' => 0,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice%23getDeviceFamily' => 0,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice%23setDeviceFamily' => 0,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice%24id' => 50,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice%24created' => 42,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice%24userClass' => 51,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice%24userId' => 52,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice%24userAgent' => 53,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice%24uaFamily' => 54,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice%24osFamily' => 55,
'Contao%5CCoreBundle%5CEntity%5CTrustedDevice%24deviceFamily' => 56,
'Contao%5CInstallationBundle%5CController%5CInstallationController' => 57,
'Contao%5CInstallationBundle%5CController%5CInstallationController%23__invoke' => 0,
'Contao%5CInstallationBundle%5CController%5CInstallationController%23initializeApplication' => 0,
'Contao%5CInstallationBundle%5CController%5CInstallationController%23acceptLicense' => 0,
'Contao%5CInstallationBundle%5CController%5CInstallationController%23setPassword' => 0,
'Contao%5CInstallationBundle%5CController%5CInstallationController%23login' => 0,
'Contao%5CInstallationBundle%5CController%5CInstallationController%23purgeSymfonyCache' => 0,
'Contao%5CInstallationBundle%5CController%5CInstallationController%23warmUpSymfonyCache' => 0,
'Contao%5CInstallationBundle%5CController%5CInstallationController%23setUpDatabaseConnection' => 0,
'Contao%5CInstallationBundle%5CController%5CInstallationController%23runDatabaseUpdates' => 0,
'Contao%5CInstallationBundle%5CController%5CInstallationController%23adjustDatabaseTables' => 0,
'Contao%5CInstallationBundle%5CController%5CInstallationController%23importExampleWebsite' => 0,
'Contao%5CInstallationBundle%5CController%5CInstallationController%23createAdminUser' => 0,
'Contao%5CInstallationBundle%5CController%5CInstallationController%23render' => 0,
'Contao%5CInstallationBundle%5CController%5CInstallationController%23trans' => 0,
'Contao%5CInstallationBundle%5CController%5CInstallationController%23getRedirectResponse' => 0,
'Contao%5CInstallationBundle%5CController%5CInstallationController%23addDefaultsToContext' => 0,
'Contao%5CInstallationBundle%5CController%5CInstallationController%23getRequestToken' => 0,
'Contao%5CInstallationBundle%5CController%5CInstallationController%23getContainerParameter' => 0,
'Contao%5CInstallationBundle%5CController%5CInstallationController%23getUserAgentString' => 0,
'Contao%5CInstallationBundle%5CController%5CInstallationController%23setContainer' => 0,
'Contao%5CInstallationBundle%5CController%5CInstallationController%24context' => 0,
'Contao%5CInstallationBundle%5CController%5CInstallationController%24container' => 0,
'Contao%5CManagerBundle%5CController%5CDebugController' => 0,
'Contao%5CManagerBundle%5CController%5CDebugController%23__construct' => 0,
'Contao%5CManagerBundle%5CController%5CDebugController%23enableAction' => 0,
'Contao%5CManagerBundle%5CController%5CDebugController%23disableAction' => 0,
'Contao%5CManagerBundle%5CController%5CDebugController%23updateJwtCookie' => 0,
'Contao%5CManagerBundle%5CController%5CDebugController%24requestStack' => 0,
'Contao%5CManagerBundle%5CController%5CDebugController%24jwtManager' => 0,
'Contao%5CManagerBundle%5CController%5CDebugController%24security' => 0,
'Doctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController' => 0,
'Doctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23__construct' => 0,
'Doctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainAction' => 0,
'Doctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainSQLitePlatform' => 0,
'Doctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainOtherPlatform' => 0,
'Doctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainOraclePlatform' => 0,
'Doctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%24twig' => 0,
'Doctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%24registry' => 0,
'Doctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%24profiler' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23__construct' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23addInsert' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getInserts' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getSelectSQL' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getCountSQL' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getInsertSQL' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getResultSetMapping' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getSelectConditionStatementSQL' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23exists' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getCacheRegion' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getEntityHydrator' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23storeEntityCache' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23storeJoinedAssociations' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getHash' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23expandParameters' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23expandCriteriaParameters' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getClassMetadata' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getManyToManyCollection' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getOneToManyCollection' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getOwningTable' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23executeInserts' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23load' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadAll' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadById' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23count' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadCriteria' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadManyToManyCollection' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadOneToManyCollection' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadOneToOneEntity' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23lock' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23refresh' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23buildCollectionCacheKey' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getCriteriaOrderings' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23mapToOrderEnumIfAvailable' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CCachedPersister%23afterTransactionComplete' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CCachedPersister%23afterTransactionRolledBack' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23update' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23delete' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24uow' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24metadataFactory' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24persister' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24class' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24queuedCache' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24region' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24timestampRegion' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24timestampKey' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24hydrator' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24cache' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24filters' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24cacheLogger' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24regionName' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24joinedAssociations' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CCachedEntityPersister' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CCachedEntityPersister%23getEntityHydrator' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CCachedEntityPersister%23storeEntityCache' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CCachedPersister%23getCacheRegion' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getClassMetadata' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getResultSetMapping' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getInserts' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getInsertSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getSelectSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getCountSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23expandParameters' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23expandCriteriaParameters' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getSelectConditionStatementSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23addInsert' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23executeInserts' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23count' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getOwningTable' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23load' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadById' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadOneToOneEntity' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23refresh' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadCriteria' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadAll' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getManyToManyCollection' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadManyToManyCollection' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadOneToManyCollection' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23lock' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getOneToManyCollection' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23exists' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23afterTransactionComplete' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23afterTransactionRolledBack' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23delete' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23update' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23updateCache' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadOnlyCachedEntityPersister' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadOnlyCachedEntityPersister%23update' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23__construct' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23afterTransactionComplete' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23afterTransactionRolledBack' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23delete' => 0,
'Doctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23update' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23prepareInsertData' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23getDiscriminatorColumnTableName' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23getSelectColumnSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23getSelectJoinColumnSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23__construct' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23isFilterHashUpToDate' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23updateFilterHash' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getClassMetadata' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getResultSetMapping' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23addInsert' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getInserts' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23executeInserts' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23assignDefaultVersionAndUpsertableValues' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23fetchVersionAndNotUpsertableValues' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23extractIdentifierTypes' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23update' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23updateTable' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23deleteJoinTableRecords' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23delete' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23prepareUpdateData' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOwningTable' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23load' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadById' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadOneToOneEntity' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23refresh' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23count' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadCriteria' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23expandCriteriaParameters' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadAll' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getManyToManyCollection' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadManyToManyCollection' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getCountSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOrderBySQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectColumnsSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectColumnAssociationSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectManyToManyJoinSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getInsertSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getInsertColumnList' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSQLTableAlias' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23lock' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getLockTablesSql' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionCriteriaSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionStatementSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOneToManyCollection' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadOneToManyCollection' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23expandParameters' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23exists' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getJoinSQLForJoinColumns' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSQLColumnAlias' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23generateFilterConditionSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23switchPersisterContext' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getClassIdentifiersTypes' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24class' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24conn' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24platform' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24em' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24queuedInserts' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24columnTypes' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24quotedColumns' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24quoteStrategy' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24identifierFlattener' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24currentPersisterContext' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23prepareInsertData' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadArrayFromResult' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadCollectionFromStatement' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getManyToManyStatement' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectColumnSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionStatementColumnSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOneToManyStatement' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23expandToManyParameters' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getCriteriaOrderings' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23mapToOrderEnumIfAvailable' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getReadLockSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getWriteLockSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24comparisonMap' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24limitsHandlingContext' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24noLimitsContext' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24filterHash' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%23__construct' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24class' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24rsm' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24selectColumnListSql' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24selectJoinSql' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24sqlAliasCounter' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24sqlTableAliases' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24handlesLimits' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getDiscriminatorColumnTableName' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getVersionedClassMetadata' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getOwningTable' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23executeInserts' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23update' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23delete' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getSelectSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getCountSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getLockTablesSql' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getSelectColumnsSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getInsertColumnList' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23assignDefaultVersionAndUpsertableValues' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23fetchVersionAndNotUpsertableValues' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getJoinSql' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getReadLockSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getWriteLockSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getSQLResultCasing' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%24owningTableMap' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%24quotedTableMap' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getDiscriminatorColumnTableName' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectColumnsSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getInsertColumnList' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSQLTableAlias' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectConditionSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectConditionCriteriaSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectConditionDiscriminatorValueSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23generateFilterConditionSQL' => 0,
'Doctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSQLResultCasing' => 0,
'Nelmio%5CSecurityBundle%5CController%5CContentSecurityPolicyController' => 0,
'Nelmio%5CSecurityBundle%5CController%5CContentSecurityPolicyController%23__construct' => 0,
'Nelmio%5CSecurityBundle%5CController%5CContentSecurityPolicyController%23indexAction' => 0,
'Nelmio%5CSecurityBundle%5CController%5CContentSecurityPolicyController%24logger' => 0,
'Nelmio%5CSecurityBundle%5CController%5CContentSecurityPolicyController%24filter' => 0,
'Nelmio%5CSecurityBundle%5CController%5CContentSecurityPolicyController%24dispatcher' => 0,
'Scheb%5CTwoFactorBundle%5CController%5CFormController' => 0,
'Scheb%5CTwoFactorBundle%5CController%5CFormController%23__construct' => 0,
'Scheb%5CTwoFactorBundle%5CController%5CFormController%23form' => 0,
'Scheb%5CTwoFactorBundle%5CController%5CFormController%23getTwoFactorToken' => 0,
'Scheb%5CTwoFactorBundle%5CController%5CFormController%23setPreferredProvider' => 0,
'Scheb%5CTwoFactorBundle%5CController%5CFormController%23getTemplateVars' => 0,
'Scheb%5CTwoFactorBundle%5CController%5CFormController%23renderForm' => 0,
'Scheb%5CTwoFactorBundle%5CController%5CFormController%23getLastAuthenticationException' => 0,
'Scheb%5CTwoFactorBundle%5CController%5CFormController%23canSetTrustedDevice' => 0,
'Scheb%5CTwoFactorBundle%5CController%5CFormController%24tokenStorage' => 0,
'Scheb%5CTwoFactorBundle%5CController%5CFormController%24providerRegistry' => 0,
'Scheb%5CTwoFactorBundle%5CController%5CFormController%24twoFactorFirewallContext' => 0,
'Scheb%5CTwoFactorBundle%5CController%5CFormController%24logoutUrlGenerator' => 0,
'Scheb%5CTwoFactorBundle%5CController%5CFormController%24trustedDeviceManager' => 0,
'Scheb%5CTwoFactorBundle%5CController%5CFormController%24trustedFeatureEnabled' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23__construct' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23redirectAction' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23urlRedirectAction' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23__invoke' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%24router' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%24httpPort' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%24httpsPort' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%23__construct' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%23templateAction' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%23__invoke' => 0,
'Symfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%24twig' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CExceptionPanelController' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CExceptionPanelController%23__construct' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CExceptionPanelController%23body' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CExceptionPanelController%23stylesheet' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CExceptionPanelController%24errorRenderer' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CExceptionPanelController%24profiler' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23__construct' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23homeAction' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23panelAction' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23toolbarAction' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23searchBarAction' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23searchResultsAction' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23searchAction' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23phpinfoAction' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23openAction' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23getTemplateManager' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23denyAccessIfProfilerDisabled' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23renderWithCspNonces' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%24templateManager' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%24generator' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%24profiler' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%24twig' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%24templates' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%24cspHandler' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%24baseDir' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CRouterController' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CRouterController%23__construct' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CRouterController%23panelAction' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CRouterController%23getTraces' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CRouterController%24profiler' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CRouterController%24twig' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CRouterController%24matcher' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CRouterController%24routes' => 0,
'Symfony%5CBundle%5CWebProfilerBundle%5CController%5CRouterController%24expressionLanguageProviders' => 0,
'Symfony%5CCmf%5CBundle%5CRoutingBundle%5CController%5CRedirectController' => 0,
'Symfony%5CCmf%5CBundle%5CRoutingBundle%5CController%5CRedirectController%23__construct' => 0,
'Symfony%5CCmf%5CBundle%5CRoutingBundle%5CController%5CRedirectController%23redirectAction' => 0,
'Symfony%5CCmf%5CBundle%5CRoutingBundle%5CController%5CRedirectController%24router' => 0,
'Symfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver' => 0,
'Symfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23__construct' => 0,
'Symfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23supports' => 0,
'Symfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23resolve' => 0,
'Symfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%24tokenStorage' => 0,

], [

0 => [],
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '%contao.backend.route_prefix%',
                ],
                'defaults' => [
                    [
                        '_scope' => 'backend',
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '',
                ],
                'name' => [
                    'contao_backend',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/login',
                ],
                'name' => [
                    'contao_backend_login',
                ],
                'defaults' => [
                    [
                        '_store_referrer' => false,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/logout',
                ],
                'name' => [
                    'contao_backend_logout',
                ],
                'defaults' => [
                    [
                        '_store_referrer' => false,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/password',
                ],
                'name' => [
                    'contao_backend_password',
                ],
                'defaults' => [
                    [
                        '_store_referrer' => false,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
6 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/confirm',
                ],
                'name' => [
                    'contao_backend_confirm',
                ],
                'defaults' => [
                    [
                        '_store_referrer' => false,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
7 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/file',
                ],
                'name' => [
                    'contao_backend_file',
                ],
                'defaults' => [
                    [
                        '_store_referrer' => false,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
8 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/help',
                ],
                'name' => [
                    'contao_backend_help',
                ],
                'defaults' => [
                    [
                        '_store_referrer' => false,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
9 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/page',
                ],
                'name' => [
                    'contao_backend_page',
                ],
                'defaults' => [
                    [
                        '_store_referrer' => false,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
10 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/popup',
                ],
                'name' => [
                    'contao_backend_popup',
                ],
                'defaults' => [
                    [
                        '_store_referrer' => false,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
11 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/alerts',
                ],
                'name' => [
                    'contao_backend_alerts',
                ],
                'defaults' => [
                    [
                        '_store_referrer' => false,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
12 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/picker',
                ],
                'name' => [
                    'contao_backend_picker',
                ],
                'defaults' => [
                    [
                        '_store_referrer' => false,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
13 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/{parameters}',
                ],
                'name' => [
                    'contao_backend_fallback',
                ],
                'requirements' => [
                    [
                        'parameters' => '.*',
                    ],
                ],
                'defaults' => [
                    [
                        '_store_referrer' => false,
                    ],
                ],
                'priority' => [
                    -1000,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
14 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '%contao.backend.route_prefix%/preview',
                ],
                'name' => [
                    'contao_backend_preview',
                ],
                'defaults' => [
                    [
                        '_scope' => 'backend',
                        '_allow_preview' => true,
                        '_store_referrer' => false,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
15 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '%contao.backend.route_prefix%/preview_switch',
                ],
                'name' => [
                    'contao_backend_switch',
                ],
                'defaults' => [
                    [
                        '_scope' => 'backend',
                        '_allow_preview' => true,
                        '_store_referrer' => false,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
16 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/_contao/captcha/{_locale}',
                ],
                'name' => [
                    'contao_frontend_captcha',
                ],
                'defaults' => [
                    [
                        '_scope' => 'frontend',
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
17 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'defaults' => [
                    [
                        '_scope' => 'frontend',
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
18 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/favicon.ico',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
19 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/_contao/cron',
                ],
                'name' => [
                    'contao_frontend_cron',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
20 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/_contao/share',
                ],
                'name' => [
                    'contao_frontend_share',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
21 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/_contao/logout',
                ],
                'name' => [
                    'contao_frontend_logout',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
22 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/_contao/check_cookies',
                ],
                'name' => [
                    'contao_frontend_check_cookies',
                ],
                'defaults' => [
                    [
                        '_token_check' => false,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
23 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/_contao/request_token_script',
                ],
                'name' => [
                    'contao_frontend_request_token_script',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
24 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/_contao/initialize',
                ],
                'name' => [
                    'contao_initialize',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
25 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Contao\\CoreBundle\\ServiceAnnotation\\Page'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Contao\\CoreBundle\\ServiceAnnotation\\Page')),
            clone $p['Contao\\CoreBundle\\ServiceAnnotation\\Page'],
            clone $p['Contao\\CoreBundle\\ServiceAnnotation\\Page'],
            clone $p['Contao\\CoreBundle\\ServiceAnnotation\\Page'],
        ],
        null,
        [
            'Contao\\CoreBundle\\ServiceAnnotation\\Page' => [
                'type' => [
                    'error_401',
                    'error_403',
                    'error_404',
                    'error_503',
                ],
                'path' => [
                    false,
                    false,
                    false,
                    false,
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
            $o[2],
            $o[3],
        ],
        []
    );
},
26 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Contao\\CoreBundle\\ServiceAnnotation\\Page'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Contao\\CoreBundle\\ServiceAnnotation\\Page')),
        ],
        null,
        [
            'Contao\\CoreBundle\\ServiceAnnotation\\Page' => [
                'contentComposition' => [
                    false,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
27 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'defaults' => [
                    [
                        '_scope' => 'frontend',
                        '_allow_preview' => true,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
28 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/_contao/preview/{id}',
                ],
                'name' => [
                    'contao_preview_link',
                ],
                'requirements' => [
                    [
                        'id' => '\\d+',
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
29 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/robots.txt',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
30 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/sitemap.xml',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
31 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Table'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Table')),
            clone ($p['Doctrine\\ORM\\Mapping\\Index'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Index')),
            clone $p['Doctrine\\ORM\\Mapping\\Index'],
            clone $p['Doctrine\\ORM\\Mapping\\Index'],
            clone ($p['Doctrine\\ORM\\Mapping\\Entity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Entity')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'tl_crawl_queue',
                    'job_id',
                    'uri_hash',
                    'processed',
                ],
                'indexes' => [
                    [
                        $o[1],
                        $o[2],
                        $o[3],
                    ],
                ],
                'columns' => [
                    1 => [
                        'job_id',
                    ],
                    [
                        'uri_hash',
                    ],
                    [
                        'processed',
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[4],
        ],
        []
    );
},
32 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Id'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Id')),
            clone ($p['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
            clone ($p['Doctrine\\ORM\\Mapping\\GeneratedValue'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\GeneratedValue')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    1 => 'integer',
                ],
                'precision' => [
                    1 => null,
                ],
                'scale' => [
                    1 => null,
                ],
                'options' => [
                    1 => [
                        'unsigned' => true,
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
            $o[2],
        ],
        []
    );
},
33 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'job_id',
                ],
                'type' => [
                    'string',
                ],
                'length' => [
                    128,
                ],
                'precision' => [
                    null,
                ],
                'scale' => [
                    null,
                ],
                'options' => [
                    [
                        'fixed' => true,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
34 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    'text',
                ],
                'precision' => [
                    null,
                ],
                'scale' => [
                    null,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
35 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'uri_hash',
                ],
                'type' => [
                    'string',
                ],
                'length' => [
                    40,
                ],
                'precision' => [
                    null,
                ],
                'scale' => [
                    null,
                ],
                'options' => [
                    [
                        'fixed' => true,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
36 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'found_on',
                ],
                'type' => [
                    'text',
                ],
                'precision' => [
                    null,
                ],
                'scale' => [
                    null,
                ],
                'nullable' => [
                    true,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
37 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    'smallint',
                ],
                'precision' => [
                    null,
                ],
                'scale' => [
                    null,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
38 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    'boolean',
                ],
                'precision' => [
                    null,
                ],
                'scale' => [
                    null,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
39 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    'text',
                ],
                'precision' => [
                    null,
                ],
                'scale' => [
                    null,
                ],
                'nullable' => [
                    true,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
40 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Table'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Table')),
            clone ($p['Doctrine\\ORM\\Mapping\\Index'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Index')),
            clone ($p['Doctrine\\ORM\\Mapping\\Entity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Entity')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'tl_cron_job',
                    'name',
                ],
                'indexes' => [
                    [
                        $o[1],
                    ],
                ],
                'columns' => [
                    1 => [
                        'name',
                    ],
                ],
                'repositoryClass' => [
                    2 => 'Contao\\CoreBundle\\Repository\\CronJobRepository',
                ],
            ],
        ],
        [
            $o[0],
            $o[2],
        ],
        []
    );
},
41 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    'string',
                ],
                'length' => [
                    255,
                ],
                'precision' => [
                    null,
                ],
                'scale' => [
                    null,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
42 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    'datetime',
                ],
                'precision' => [
                    null,
                ],
                'scale' => [
                    null,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
43 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Table'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Table')),
            clone ($p['Doctrine\\ORM\\Mapping\\Index'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Index')),
            clone ($p['Doctrine\\ORM\\Mapping\\UniqueConstraint'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\UniqueConstraint')),
            clone ($p['Doctrine\\ORM\\Mapping\\Entity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Entity')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'tl_remember_me',
                    'series',
                    'value',
                ],
                'indexes' => [
                    [
                        $o[1],
                    ],
                ],
                'uniqueConstraints' => [
                    [
                        $o[2],
                    ],
                ],
                'columns' => [
                    1 => [
                        'series',
                    ],
                    [
                        'value',
                    ],
                ],
                'repositoryClass' => [
                    3 => 'Contao\\CoreBundle\\Repository\\RememberMeRepository',
                ],
            ],
        ],
        [
            $o[0],
            $o[3],
        ],
        []
    );
},
44 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    'binary_string',
                ],
                'length' => [
                    32,
                ],
                'precision' => [
                    null,
                ],
                'scale' => [
                    null,
                ],
                'options' => [
                    [
                        'fixed' => true,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
45 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    'binary_string',
                ],
                'length' => [
                    64,
                ],
                'precision' => [
                    null,
                ],
                'scale' => [
                    null,
                ],
                'options' => [
                    [
                        'fixed' => true,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
46 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    'datetime',
                ],
                'precision' => [
                    null,
                ],
                'scale' => [
                    null,
                ],
                'nullable' => [
                    true,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
47 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    'string',
                ],
                'length' => [
                    100,
                ],
                'precision' => [
                    null,
                ],
                'scale' => [
                    null,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
48 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    'string',
                ],
                'length' => [
                    200,
                ],
                'precision' => [
                    null,
                ],
                'scale' => [
                    null,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
49 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Entity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Entity')),
            clone ($p['Doctrine\\ORM\\Mapping\\Table'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Table')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    1 => 'tl_trusted_device',
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
50 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Id'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Id')),
            clone ($p['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
            clone ($p['Doctrine\\ORM\\Mapping\\GeneratedValue'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\GeneratedValue')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    1 => 'integer',
                ],
                'precision' => [
                    1 => null,
                ],
                'scale' => [
                    1 => null,
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
            $o[2],
        ],
        []
    );
},
51 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    'string',
                ],
                'precision' => [
                    null,
                ],
                'scale' => [
                    null,
                ],
                'nullable' => [
                    true,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
52 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    'integer',
                ],
                'precision' => [
                    null,
                ],
                'scale' => [
                    null,
                ],
                'nullable' => [
                    true,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
53 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'user_agent',
                ],
                'type' => [
                    'text',
                ],
                'precision' => [
                    null,
                ],
                'scale' => [
                    null,
                ],
                'nullable' => [
                    true,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
54 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'ua_family',
                ],
                'type' => [
                    'string',
                ],
                'precision' => [
                    null,
                ],
                'scale' => [
                    null,
                ],
                'nullable' => [
                    true,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
55 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'os_family',
                ],
                'type' => [
                    'string',
                ],
                'precision' => [
                    null,
                ],
                'scale' => [
                    null,
                ],
                'nullable' => [
                    true,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
56 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'device_family',
                ],
                'type' => [
                    'string',
                ],
                'precision' => [
                    null,
                ],
                'scale' => [
                    null,
                ],
                'nullable' => [
                    true,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
57 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '%contao.backend.route_prefix%/install',
                ],
                'name' => [
                    'contao_install',
                ],
                'defaults' => [
                    [
                        '_scope' => 'backend',
                        '_store_referrer' => false,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},

]];
