<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUvhmO5C\Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUvhmO5C/Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer.php') {
    touch(__DIR__.'/ContainerUvhmO5C.legacy');

    return;
}

if (!\class_exists(Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, false)) {
    \class_alias(\ContainerUvhmO5C\Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, false);
}

return new \ContainerUvhmO5C\Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer([
    'container.build_hash' => 'UvhmO5C',
    'container.build_id' => 'fc0d1c1c',
    'container.build_time' => 1762296506,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUvhmO5C');
