<?php

namespace ContainerOHekiaa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioSecurity_UaParser_UaPhp_ProviderService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private 'nelmio_security.ua_parser.ua_php.provider' shared service.
     *
     * @return \UAParser\Parser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ua-parser/uap-php/src/AbstractParser.php';
        include_once \dirname(__DIR__, 4).'/vendor/ua-parser/uap-php/src/ParserFactoryMethods.php';
        include_once \dirname(__DIR__, 4).'/vendor/ua-parser/uap-php/src/Parser.php';

        return $container->privates['nelmio_security.ua_parser.ua_php.provider'] = \UAParser\Parser::create();
    }
}
