<?php

namespace ContainerHWxNX89;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Logout_Listener_LegacyHandler_0Service extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private 'security.logout.listener.legacy_handler.0' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\LegacyLogoutHandlerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Security/LegacyLogoutHandlerListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Logout/LogoutHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/manager-bundle/src/Security/Logout/LogoutHandler.php';

        return $container->privates['security.logout.listener.legacy_handler.0'] = new \Symfony\Bundle\SecurityBundle\Security\LegacyLogoutHandlerListener(new \Contao\ManagerBundle\Security\Logout\LogoutHandler(($container->services['contao_manager.jwt_manager'] ?? $container->get('contao_manager.jwt_manager', 3))));
    }
}
