<?php

namespace ContainerUvhmO5C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Command_VersionService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'contao.command.version' shared service.
     *
     * @return \Contao\CoreBundle\Command\VersionCommand
     *
     * @deprecated Since contao/core-bundle 4.4: Using the "contao.command.version" service ID has been deprecated and will no longer work in Contao 5.0.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('contao/core-bundle', '4.4', 'Using the "contao.command.version" service ID has been deprecated and will no longer work in Contao 5.0.');

        $container->privates['contao.command.version'] = $instance = new \Contao\CoreBundle\Command\VersionCommand();

        $instance->setName('contao:version');
        $instance->setDescription('Outputs the contao/core-bundle version (deprecated).');

        return $instance;
    }
}
