<?php

namespace ContainerUvhmO5C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosHttpCache_EventListener_InvalidationService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'fos_http_cache.event_listener.invalidation' shared service.
     *
     * @return \FOS\HttpCacheBundle\EventListener\InvalidationListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/http-cache-bundle/src/EventListener/InvalidationListener.php';

        $a = ($container->services['fos_http_cache.cache_manager'] ?? $container->getFosHttpCache_CacheManagerService());

        if (isset($container->privates['fos_http_cache.event_listener.invalidation'])) {
            return $container->privates['fos_http_cache.event_listener.invalidation'];
        }
        $b = ($container->services['router'] ?? $container->getRouterService());

        if (isset($container->privates['fos_http_cache.event_listener.invalidation'])) {
            return $container->privates['fos_http_cache.event_listener.invalidation'];
        }

        return $container->privates['fos_http_cache.event_listener.invalidation'] = new \FOS\HttpCacheBundle\EventListener\InvalidationListener($a, $b, ($container->privates['fos_http_cache.rule_matcher.must_invalidate'] ?? $container->getFosHttpCache_RuleMatcher_MustInvalidateService()), NULL);
    }
}
