<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOHekiaa\Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOHekiaa/Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOHekiaa.legacy');

    return;
}

if (!\class_exists(Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOHekiaa\Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, false);
}

return new \ContainerOHekiaa\Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer([
    'container.build_hash' => 'OHekiaa',
    'container.build_id' => '24ed788c',
    'container.build_time' => 1762296505,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOHekiaa');
